include:
  - project: acc-co/devops/python/acc-py-devtools
    file: acc_py_devtools/templates/gitlab-ci/python.yml

variables:
  project_dir: src/cernml/
  project_name: cernml-coi-utils
  acc_py_image: registry.cern.ch/acc/acc-py_cc7_openjdk11_ci:2020.11
  PY_VERSION: "3.7"

# Build: Create a wheel to speed up installation.

build_wheel:
  extends:
    - .acc_py_build_wheel

# Test: Run linters and unit tests. Run tests both in-tree and out-of-tree.

test_lint:
  stage: test
  image: ${acc_py_image}
  before_script:
    - python -m pip install -e '.[lint]'
  script:
    - cd ${project_root}
    - ./run_linters.sh ${project_dir}/*

test_dev:
  extends: .acc_py_dev_test
  image: ${acc_py_image}
  script:
    - cd ${project_root}
    - python -m pytest --cov=${project_dir} --junitxml=report.xml

test_install:
  extends: .acc_py_full_test
  image: ${acc_py_image}
  script:
    - pip install -e '.[test]'
    - cd ${project_root}/tests
    - pytest

# Docs: Build and publish docs, which has to import all packages.

build_docs:
  extends: .acc_py_build_docs
  image: ${acc_py_image}
  before_script:
    - yum -y install graphviz curl

build_docs_on_tag:
  extends: .acc_py_build_docs_on_tag
  image: ${acc_py_image}
  before_script:
    - yum -y install graphviz curl

# Deploy: Publish the wheel on acc-py-repo.cern.ch.

release_wheel:
  extends: .acc_py_release_wheel
