# SPDX-FileCopyrightText: 2020-2023 CERN
# SPDX-FileCopyrightText: 2023 GSI Helmholtzzentrum für Schwerionenforschung
# SPDX-FileNotice: All rights not expressly granted are reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later OR EUPL-1.2+

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
    args: ["--unsafe"]
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
- repo: https://github.com/fsfe/reuse-tool
  rev: v3.1.0a1
  hooks:
    - id: reuse
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-length
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
  - id: mypy
    exclude: ^docs/conf.py
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: ["python"]
    args: ["-rn", "-sn", "-j0"]
